base_url = "https://www.owenyoung.com"
build_search_index = false
compile_sass = false
default_language = "zh"
description = "主要关注技术，读书，摘抄，杂谈，文章评论，工具分享，工作流，灵感，英文学习，注意力管理，深度工作等方向"
generate_feed = true
generate_rss = true
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20},
  {name = "categories", feed = true, paginate_by = 20},
]
title = "Owen Young's Blog"

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
highlight_theme = "Tomorrow"
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true
smart_punctuation = true
[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = false

[extra]
author = "Owen Young"
email = "owen@owenyoung.com"
theme_color = "#000084"

### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
github_user = "theowenyoung"
image = "https://www.owenyoung.com/logo.png"
twitter_user = "TheOwenYoung"
# gitlab_user = ""

### I18N WORDS

[slugify]
anchors = "on"
paths = "on"
taxonomies = "on"

[languages.zh]
build_search_index = true
description = "主要关注技术，读书，摘抄，杂谈，文章评论，工具分享，工作流，灵感，英文学习，注意力管理，深度工作等方向"
title = "Owen的博客"

[languages.zh.translations]
keywords = "注意力, 读书, 工具分享, 纯文本, 英语学习"
label_all_posts = "[点击查看所有文章](/blog/)"
label_archive = "全部文章归档"
label_back_to_start = "正文开始"
label_book_author = "图书作者"
label_categories = "所有分类"
label_category = "分类"
label_created = "发布于"
label_home = "首页"
label_links = "一些可能有用的链接"
label_new_posts_list_title = "以下是我[最新](/blog/)的5篇文章："
label_notes_title = "以下是我长期在[更新和维护的笔记](/categories/notes/)："
label_published_on = "发布在"
label_rating = "评分"
label_read_more = "继续阅读需要"
label_reading = "阅读时间"
label_rss = "订阅RSS"
label_table_contents = "快速导航"
label_tag = "标签"
label_tags = "标签"
label_target_language = "English Blog"
label_taxonomy = "类别"
label_thoughts_title = "以下是我最新的几条[短想法](/thoughts/)："
label_updated = "最后更新时间"
[languages.en]
description = "Mainly focus on technology, reading, excerpts, miscellaneous, article review, tool sharing, workflow, inspiration, English learning, attention management, deep work and other directions"
generate_feed = true
generate_rss = true
highlight_code = true
smart_punctuation = true
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20},
  {name = "categories", feed = true, paginate_by = 20},
]
title = "Owen Young's Blog"
[languages.en.translations]
keywords = "Focus, Reading, Tool sharing, Plain text, English learning"
label_all_posts = "[View all posts](/blog/)"
label_archive = "Archive"
label_back_to_start = "Get Started"
label_book_author = "Book Author"
label_categories = "Categories"
label_category = "Category"
label_created = "Published"
label_home = "Home"
label_links = "Links"
label_new_posts_list_title = "Here are my [latest](/en/blog/) 5 articles:"
label_notes_title = "Here are the notes I have been [updating and maintaining for a long time](/en/categories/notes/):"
label_published_on = "on"
label_rating = "Rating"
label_read_more = "Continue to Read"
label_reading = "Reading Time"
label_rss = "Subscribe RSS"
label_table_contents = "On this page"
label_tag = "Tag"
label_tags = "Tags"
label_target_language = "中文博客"
label_taxonomy = "Taxonomy"
label_thoughts_title = "Here are a few of my latest [short thoughts](/en/thoughts/)："
label_updated = "Updated"
