base_url = "https://www.owenyoung.com"
build_search_index = false
compile_sass = false
default_language = "zh"
description = "ä¸»è¦å…³æ³¨æ³¨æ„åŠ›ç®¡ç†ï¼Œæ·±åº¦å·¥ä½œï¼Œè‹±æ–‡å­¦ä¹ ï¼Œåç›´è§‰, æŠ€æœ¯ï¼Œè¯»ä¹¦ï¼Œæ‘˜æŠ„ï¼Œæ‚è°ˆï¼Œæ–‡ç« è¯„è®ºï¼Œå·¥å…·åˆ†äº«ï¼Œå·¥ä½œæµï¼Œçµæ„Ÿï¼Œç­‰æ–¹å‘"
generate_feed = true
generate_rss = true
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20},
  {name = "categories", feed = true, paginate_by = 20},
]
title = "Owen Young's Blog"

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
# highlight_theme = "Tomorrow"
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true
smart_punctuation = true
[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = false

[extra]
author = "Owen Young"
email = "owen@owenyoung.com"
theme_color = "#EA4C89"

### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
edit_url_prefix = "https://github.com/theowenyoung/blog/tree/main/content/"
github_user = "theowenyoung"
image = "https://www.owenyoung.com/logo.png"
twitter_user = "TheOwenYoung"
# gitlab_user = ""

### I18N WORDS

[slugify]
anchors = "on"
paths = "on"
taxonomies = "on"

[languages.zh]
build_search_index = true
description = "ä¸»è¦å…³æ³¨æŠ€æœ¯ï¼Œè¯»ä¹¦ï¼Œæ‘˜æŠ„ï¼Œæ‚è°ˆï¼Œæ–‡ç« è¯„è®ºï¼Œå·¥å…·åˆ†äº«ï¼Œå·¥ä½œæµï¼Œçµæ„Ÿï¼Œè‹±æ–‡å­¦ä¹ ï¼Œæ³¨æ„åŠ›ç®¡ç†ï¼Œæ·±åº¦å·¥ä½œç­‰æ–¹å‘"
title = "Owençš„åšå®¢"

[languages.zh.translations]
keywords = "æ³¨æ„åŠ›, è¯»ä¹¦, å·¥å…·åˆ†äº«, çº¯æ–‡æœ¬, è‹±è¯­å­¦ä¹ "
label_all_posts = "[ç‚¹å‡»æŸ¥çœ‹æ‰€æœ‰æ–‡ç« ğŸ”¥ğŸ”¥](/blog/)"
label_all_thoughts = "[ç‚¹å‡»æŸ¥çœ‹æ‰€æœ‰çŸ­æƒ³æ³•ğŸ”¥ğŸ”¥](/thoughts/)"
label_archive = "å…¨éƒ¨æ–‡ç« å½’æ¡£"
label_back_to_start = "æ­£æ–‡å¼€å§‹"
label_book_author = "å›¾ä¹¦ä½œè€…"
label_books = "å…¨éƒ¨ä¹¦è¯„"
label_categories = "æ‰€æœ‰åˆ†ç±»"
label_category = "åˆ†ç±»"
label_created = "å‘å¸ƒäº"
label_edit = "å¸®æˆ‘å®Œå–„è¿™ä¸ªé¡µé¢ï¼Ÿ"
label_home = "é¦–é¡µ"
label_latest_notes_title = "[æœ€è¿‘æ›´æ–°çš„10ç¯‡ç¬”è®°](/categories/notes/)ï¼š"
label_links = "ä¸€äº›å¯èƒ½æœ‰ç”¨çš„é“¾æ¥"
label_new_posts_list_title = "[æœ€æ–°](/blog/)çš„5ç¯‡æ–‡ç« ï¼š"
label_notes_title = "[å…¨éƒ¨ç¬”è®°(æŒ‰æœ€åæ›´æ–°æ—¶é—´æ’åº)](/categories/notes/)ï¼š"
label_published_on = "å‘å¸ƒåœ¨"
label_rating = "æˆ‘çš„è¯„åˆ†"
label_read_more = "ç»§ç»­é˜…è¯»éœ€è¦"
label_reading = "é˜…è¯»æ—¶é—´"
label_rss = "è®¢é˜…RSS"
label_table_contents = "å¿«é€Ÿå¯¼èˆª"
label_tag = "æ ‡ç­¾"
label_tags = "æ ‡ç­¾"
label_target_language = "English Blog"
label_taxonomy = "ç±»åˆ«"
label_thoughts_title = "æœ€æ–°çš„å‡ æ¡[çŸ­æƒ³æ³•](/thoughts/)ï¼š"
label_updated = "æœ€åæ›´æ–°æ—¶é—´"
[languages.en]
description = "Mainly focus on technology, reading, excerpts, miscellaneous, article review, tool sharing, workflow, inspiration, English learning, attention management, deep work and other directions"
generate_feed = true
generate_rss = true
highlight_code = true
smart_punctuation = true
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20},
  {name = "categories", feed = true, paginate_by = 20},
]
title = "Owen Young's Blog"
[languages.en.translations]
keywords = "Focus, Reading, Tool sharing, Plain text, English learning"
label_all_posts = "[View all posts](/en/blog/)"
label_all_thoughts = "[View all thoughtsğŸ”¥ğŸ”¥](/en/thoughts/)"
label_archive = "Archive"
label_back_to_start = "Get Started"
label_book_author = "Book Author"
label_books = "All books reviews"
label_categories = "Categories"
label_category = "Category"
label_created = "Published"
label_edit = "Edit this page"
label_home = "Home"
label_latest_notes_title = "[Recently Updated](/categories/notes/)ï¼š"
label_links = "Links"
label_new_posts_list_title = "[Latest](/en/blog/) Articles:"
label_notes_title = "All Notes [(sort by update time)](/en/categories/notes/):"
label_published_on = "on"
label_rating = "Rating"
label_read_more = "Continue to Read"
label_reading = "Reading Time"
label_rss = "Subscribe RSS"
label_table_contents = "On this page"
label_tag = "Tag"
label_tags = "Tags"
label_target_language = "ä¸­æ–‡åšå®¢"
label_taxonomy = "Taxonomy"
label_thoughts_title = "Latest [Short Thoughts](/en/thoughts/)ï¼š"
label_updated = "Updated"
